### ISSUE TITLE
I am using this XDKAirMenu for showing menu in my home controller.I have to signIn to come to this Homecontroller.Form there i can choose different options,for example My Profile and i have a sign out option there.So problem i am facing is that when logge

### ISSUE THREAD

**Issue by Abhishekg219** [XavierDK/XDKAirMenu#2]

**Comment by Abhishekg219** [comment]
Is there any1 to help me out.

**Comment by XavierDK** [comment]
If I understand, you want to add a specific control when an element is selected.
To doing this just put : 

```
- (void)viewDidLoad
{
    [super viewDidLoad];

    XDKAirMenuController *menuCtr  = [XDKAirMenuController sharedMenu];
    menuCtr.airDelegate = self;

    [self.view addSubview:menuCtr.view];
    [self addChildViewController:menuCtr];

   // Add this line
    self.tableView.delegate = self;
   //
}
```

With that, you will force the delegate of your tableView to be your controller.

Then, you can do :   

```
 - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
 {
        if (indexPath.row == 5) // For example
            [self logout];
        else
            [((id<UITableViewDelegate>)menuCtr) tableView:tableView didSelectRowAtIndexPath:indexPath];
 }
```

This will be simplified in the next version.

Hope it's help.

**Comment by Abhishekg219** [comment]
Hello Xavier,
I thought you didn't understand my point completely.I want to put a Tab
like My Account inside that controller i am logging out.Problem i am facing
is after logging out i am always redirected to the My Account.
With Regards
Abhishek Kumar

**Comment by Abhishekg219** [comment]
- (UIViewController_)airMenu:(XDKAirMenuController_)airMenu
  viewControllerAtIndexPath:(NSIndexPath*)indexPath

{

```
UIStoryboard *storyboard = self.storyboard;

UIViewController *vc = nil;



vc.view.autoresizesSubviews = TRUE;

vc.view.autoresizingMask = UIViewAutoresizingFlexibleWidth|
```

UIViewAutoresizingFlexibleHeight;

```
if (indexPath.row == 2)

{

    vc = [storyboard instantiateViewControllerWithIdentifier:
```

@"ViewController2"];

```
    return vc;//This is going to My Account And their i am logging out

}
```

   // else if (indexPath.row == 3)

```
//{

  //  vc = [storyboard instantiateViewControllerWithIdentifier:@
```

"ViewController3"];

```
   // return vc;

//}

else

{

    vc = [storyboard instantiateViewControllerWithIdentifier:
```

@"ViewController1"];

```
    return vc;//This goes to home

}
```

}

}

**Comment by jitenparmar341** [comment]
Facing the same issue plz help in this thing...

**Comment by Abhishekg219** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.
- abhishek

Accept: http://www.linkedin.com/blink?simpleRedirect=3gOc34MdzsPcj0Md3oQdzgPejkZh4BKrSBQonhFtCVF9CcOjBwNrRdyfnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4Cdj8JcSdMsCcMcCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8266718432_1&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=3kObjdzs79zc39Fbn9KpSZUoyQZp6BB9zwViDpBdj1eintmqn0Mr4tQoARkcSFGoQxktCoPoAtHmkJShlANsBFEi7oTl6Zqq7dBukJMkCRgpnhBc3p6pTdoiRt2e5FIdP9mdlpmumlEnTpWiCF1iQZyil0Nl6ZWrn5MmB55m54NsP9biRxWrSdIpPsTj5xjh2R1iRdzoCFyrmB9kRtEpCBcqjpLiSJqtSNlgk51gl1epB5DiR9Krnh6kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCdj8JcSdMsCcMcCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8266718432_1&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zkObjdzs79zc39Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by Abhishekg219** [comment]
abhishek kumar would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=3gOc34MdzsPcj0Md3oQdzgPejkZh4BKrSBQonhFtCVF9CcOjBwNrRdyfnBBiShBsC5EsOoVclZMu6lvtCVFfmJB9D9Bp6VFrmlObnhMpmdzoiRybmtSrCBvrmRLoORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4Ce3kJsz8Scz4PcCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8266718432_1&markAsRead=

View abhishek kumar&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9zwRbn8Odz8NcP9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kVej4OejgSbj8RoS4QcPtCc64Op31Bej0QpCgUejBAcmlBcSpypz9yej8Te3tzejsJe3AQcPsRe38Jqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zgOc34MdzsPcj0Md3oQdzgPejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9zwRbn8Odz8NcP9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=e3kJsz8Scz4PcCAJsCVDrTxybjRAqmkCik5ohQplenANiAhqcjlne7kPtPxlu2QRh5dGnSlyq79gkkV3cCdagRwRiAVbukF3hkVqbnlBh5Fim6h5ckZerCV7rQwUjQ9Bhn9GrAQRh7FSgPBAoTAPoPtvtDl1rBxjkn0TjTlat4wVej5Juk5iqjBxskUNbl5Edzdhj5lUuChPt7cTjDoUp45TdCwTq4cSr5l1gk5Ds7F3uAdQmz5Jp4thgjRAqmZI9zANnT1UplZSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCe3kJsz8Scz4PcCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8266718432_1&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zwRbn8Odz8NcP9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by Abhishekg219** [comment]
abhishek kumar would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=3gOc34MdzsPcj0Md3oQdzgPejkZh4BKrSBQonhFtCVF9CcOjBwNrRdyfnBBiShBsC5EsOoVclZMu6lvtCVFfmJB9D9Bp6VFrmlObnhMpmdzoiRybmtSrCBvrmRLoORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4CpzoJp6tHdn5ycCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I8266718432_1&markAsRead=

View abhishek kumar&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CoSbmhDqPlNoz9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kVej4OejgSbj8RoS4QcPtCc64Op31Bej0QpCgUejBAcmlBcSpypz9yej8Te3tzejsJe3AQcPsRe38Jqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zgOc34MdzsPcj0Md3oQdzgPejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CoSbmhDqPlNoz9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=pzoJp6tHdn5ycCAJsCVDrTxybjRAqmkCildpgR4TgQp5rORQujdkoThRk7looCdyqkN6tzlFskRgiTddsmpGkB98unlemAwNkRdUc7lSrmFOrCpilSFli39hjB5alDdHikdUm5FnpAxnqiRocD11hD52l4t4dBwRlnpCrSBJd4FSkmVIek9NenFjqRxPknllkBtad6Nqdjl4r38PqThvslx6ozpzrlBqrll1gk5hmjtHsmJEhAtVukthgjRAqmZI9zANnT1UplZSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCpzoJp6tHdn5ycCAJsCVDrTxybjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I8266718432_1&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CoSbmhDqPlNoz9Fbn9KpSZUoyQZpjYOtyZBbSRLoOVKqmhBqSVFr2VTtTsLbPFMt7hE&msgID=I8266718432_1&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
